#define UNICODE
#define _UNICODE
#include <windows.h>
#include <windowsx.h>
#include <shellapi.h>
#include <wchar.h>
#include <vector>
#include <utility>
#include <tuple>
#include <string>
#include <algorithm>
